language: python
sudo: required
python:
    - 2.7
cache:
    pip: true
    apt: true
    directories:
        - application/node_modules
        - libraries/opencv_build
before_install:
    - sudo apt-get --purge autoremove postgresql-9.2 postgresql-contrib-9.2
    - sudo apt-get --purge autoremove postgresql-9.3 postgresql-contrib-9.3
    - sudo apt-get --purge autoremove postgresql-9.4 postgresql-contrib-9.4
    - sudo apt-get --purge autoremove postgresql-9.5 postgresql-contrib-9.5
install:
    - bash install.sh
script:
    - pytest --ignore=libraries/