language: python
sudo: required
python:
    - 2.7
cache:
    pip: true
    apt: true
    directories:
        - application/node_modules
        - libraries/opencv_build
install:
    - bash install.sh
script:
    - pytest --ignore=libraries/