language: python
sudo: required
python:
    - 2.7
cache:
    pip: true
    apt: true
    directories:
        - application/node_modules
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python-dev python-pip
install:
    - pip install -r requirements.txt
    - pip install fake_rpi
    - cd application && npm install && npm run build && cd ..
script:
    - pytest