language: python
sudo: required
python:
    - 2.7
before_install:
    - sudo apt-get --purge autoremove postgresql-9.2 postgresql-contrib-9.2
    - sudo apt-get --purge autoremove postgresql-9.3 postgresql-contrib-9.3
    - sudo apt-get --purge autoremove postgresql-9.4 postgresql-contrib-9.4
    - sudo apt-get --purge autoremove postgresql-9.5 postgresql-contrib-9.5
install:
    - bash install.sh
before_script:
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/site-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7.13/lib
    - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages
    - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7.13/lib/python2.7/dist-packages
script:
    - pytest